# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Kinetics Toolkit
author: Félix Chénier
copyright: 2020-2022
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

html:
  favicon                   : ""  # A path to a favicon image
  use_edit_page_button      : false  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : false  # Whether to add a link to your repository button
  use_issues_button         : false  # Whether to add an "open an issue" button
  use_multitoc_numbering    : true   # Continuous numbering across parts/chapters
  extra_navbar              : Powered by <a href="https://jupyterbook.org">Jupyter Book</a>  # Will be displayed underneath the left navbar.
  extra_footer              : ""  # Will be displayed underneath the footer.
  google_analytics_id       : ""  # A GA id that can be used to track book views.
  home_page_in_navbar       : true  # Whether to include your home page in the left Navigation Bar
  baseurl                   : "https://kineticstoolkit.uqam.ca/doc/"  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  comments:
    hypothesis              : false
    utterances              : false

launch_buttons:
  notebook_interface        : classic  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : https://mybinder.org  # The URL of the BinderHub (e.g., https://mybinder.org)
  jupyterhub_url            : ""  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  thebe                     : false  # Add a thebe button to pages (requires the repository to run on Binder)
  colab_url                 : "" # The URL of Google Colab
  

parse:
  myst_substitutions:
    "stub": |
      ```{admonition} Section in development
      :class: admonition-stub
      This section is still only a stub. Please feel free to [contribute](dev_contributing.md).
      ```
    "incomplete": |
      ```{admonition} Incomplete section
      Some elements of this section are incomplete or out of date. Please feel free to [contribute](dev_contributing.md).
      ```
    "dev": |    
      ```{warning}
      This section refers to unstable code. This code may not be tested, and the whole API and behaviour is expected to change in the future. Do not use this code for your research.
      ```


sphinx:
  extra_extensions:
  - 'sphinx.ext.autodoc'     # Document objects using docstrings in API
  - 'sphinx.ext.autosummary' # Generate summary table pages (for autodoc)
  - 'sphinx.ext.napoleon'    # Parse numpy-style docstrings (for autodoc)
  - 'sphinx.ext.viewcode'
  - 'sphinx.ext.ifconfig'    # Allow conditional contents for master vs stable versions
  - 'sphinx_autodoc_typehints'
  - 'sphinxcontrib.mermaid'
  - 'myst_nb'
  - 'custom-directives'

  config:
    add_module_names: False
    autosummary_generate: True
    napoleon_google_docstring: False
    napoleon_numpy_docstring: True
    napoleon_include_init_with_doc: False
    napoleon_include_private_with_doc: False
    napoleon_include_special_with_doc: False
    napoleon_use_admonition_for_examples: False
    napoleon_use_admonition_for_notes: True
    napoleon_use_admonition_for_references: True
    napoleon_use_ivar: False
    napoleon_use_param: True
    napoleon_use_rtype: True
    templates_path: ['_templates']
    exclude_patterns:
      - '_build'
      - 'Thumbs.db'
      - '.DS_Store'
      - '.ipynb_checkpoints'
      - 'api/external.*'
      - 'api/kineticstoolkit.external.*'
      - 'toc.md'

    html_theme_options:
      'logo_only': True  # default False
      'collapse_navigation': True
      'navigation_depth': 4
